language: node_js
node_js:
  - 5.1.1
  - 4.2.3
before_script:
  - npm install -g grunt-cli
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: change
